version: '3.8'

services:
  db:
    container_name: db-new-cs
    image: 'postgres:9.5'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=campsocialdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/campsocialdb/
    volumes:
      - ./aux_dirs/postgres_data:/var/lib/postgresql/data
    
      
  elastic:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node
      
