logging.level:
  root: warn
  br.ufrrj.labweb.campussocial: debug
  org.springframework:
    data: info
    data.elasticsearch: info

br:
  ufrrj:
    labweb:
      campussocial:
        elastic-search-host: localhost:9200
